
// This file is generated by src/Tools/generateTemaplates/templateClassPyExport.py out of the XML file
// Every change you make here gets lost in the next full rebuild!
#ifndef GUI_VIEWPROVIDERPY_H
#define GUI_VIEWPROVIDERPY_H

#include <App/ExtensionContainerPy.h>
#include <Gui/ViewProvider.h>
#include <string>

namespace Gui
{

//===========================================================================
// ViewProviderPy - Python wrapper
//===========================================================================

/** The python export class for ViewProvider
 */
class GuiExport ViewProviderPy : public App::ExtensionContainerPy
{
protected:
    ~ViewProviderPy();

public:
    static PyTypeObject   Type;
    static PyMethodDef    Methods[];
    static PyGetSetDef    GetterSetter[];
    virtual PyTypeObject *GetType(void) {return &Type;}

public:
    ViewProviderPy(ViewProvider *pcObject, PyTypeObject *T = &Type);
    static PyObject *PyMake(struct _typeobject *, PyObject *, PyObject *);
    virtual int PyInit(PyObject* args, PyObject*k);


    typedef ViewProvider* PointerType ;

    virtual PyObject *_repr(void);        // the representation
    std::string representation(void) const;

    /** @name callbacks and implementers for the python object methods */
    //@{
    /// callback for the addProperty() method
    static PyObject * staticCallback_addProperty (PyObject *self, PyObject *args);
    /// implementer for the addProperty() method
    PyObject*  addProperty(PyObject *args);
    /// callback for the removeProperty() method
    static PyObject * staticCallback_removeProperty (PyObject *self, PyObject *args);
    /// implementer for the removeProperty() method
    PyObject*  removeProperty(PyObject *args);
    /// callback for the supportedProperties() method
    static PyObject * staticCallback_supportedProperties (PyObject *self, PyObject *args);
    /// implementer for the supportedProperties() method
    PyObject*  supportedProperties(PyObject *args);
    /// callback for the show() method
    static PyObject * staticCallback_show (PyObject *self, PyObject *args);
    /// implementer for the show() method
    PyObject*  show(PyObject *args);
    /// callback for the hide() method
    static PyObject * staticCallback_hide (PyObject *self, PyObject *args);
    /// implementer for the hide() method
    PyObject*  hide(PyObject *args);
    /// callback for the isVisible() method
    static PyObject * staticCallback_isVisible (PyObject *self, PyObject *args);
    /// implementer for the isVisible() method
    PyObject*  isVisible(PyObject *args);
    /// callback for the addDisplayMode() method
    static PyObject * staticCallback_addDisplayMode (PyObject *self, PyObject *args);
    /// implementer for the addDisplayMode() method
    PyObject*  addDisplayMode(PyObject *args);
    /// callback for the listDisplayModes() method
    static PyObject * staticCallback_listDisplayModes (PyObject *self, PyObject *args);
    /// implementer for the listDisplayModes() method
    PyObject*  listDisplayModes(PyObject *args);
    /// callback for the toString() method
    static PyObject * staticCallback_toString (PyObject *self, PyObject *args);
    /// implementer for the toString() method
    PyObject*  toString(PyObject *args);
    /// callback for the setTransformation() method
    static PyObject * staticCallback_setTransformation (PyObject *self, PyObject *args);
    /// implementer for the setTransformation() method
    PyObject*  setTransformation(PyObject *args);
    /// callback for the claimChildren() method
    static PyObject * staticCallback_claimChildren (PyObject *self, PyObject *args);
    /// implementer for the claimChildren() method
    PyObject*  claimChildren(PyObject *args);
    //@}


    /** @name callbacks and implementers for the python object attributes */
    //@{
    ///getter callback for the Annotation attribute
    static PyObject * staticCallback_getAnnotation (PyObject *self, void *closure);
    /// getter for the Annotation attribute
    Py::Object getAnnotation(void) const;
    /// setter callback for the Annotation attribute
    static int staticCallback_setAnnotation (PyObject *self, PyObject *value, void *closure);
    /// setter for the Annotation attribute
    void setAnnotation(Py::Object arg);
    ///getter callback for the Icon attribute
    static PyObject * staticCallback_getIcon (PyObject *self, void *closure);
    /// getter for the Icon attribute
    Py::Object getIcon(void) const;
    /// setter callback for the Icon attribute
    static int staticCallback_setIcon (PyObject *self, PyObject *value, void *closure);
    // no setter method,  Icon is read only!
    ///getter callback for the RootNode attribute
    static PyObject * staticCallback_getRootNode (PyObject *self, void *closure);
    /// getter for the RootNode attribute
    Py::Object getRootNode(void) const;
    /// setter callback for the RootNode attribute
    static int staticCallback_setRootNode (PyObject *self, PyObject *value, void *closure);
    /// setter for the RootNode attribute
    void setRootNode(Py::Object arg);
    ///getter callback for the IV attribute
    static PyObject * staticCallback_getIV (PyObject *self, void *closure);
    /// getter for the IV attribute
    Py::String getIV(void) const;
    /// setter callback for the IV attribute
    static int staticCallback_setIV (PyObject *self, PyObject *value, void *closure);
    // no setter method,  IV is read only!
    //@}

    /// getter method for special attributes (e.g. dynamic ones)
    PyObject *getCustomAttributes(const char* attr) const;
    /// setter for special attributes (e.g. dynamic ones)
    /// Output: Success=1, Failure=-1, Ignore=0
    int setCustomAttributes(const char* attr, PyObject *obj);
    PyObject *_getattr(const char *attr);              // __getattr__ function
    int _setattr(const char *attr, PyObject *value);        // __setattr__ function

    /// getter for the object handled by this class
    ViewProvider *getViewProviderPtr(void) const;

    /** @name additional declarations and methods for the wrapper class */
    //@{

    //@}
};

}  //namespace Gui

#endif  // GUI_VIEWPROVIDERPY_H


