
// This file is generated by src/Tools/generateTemaplates/templateClassPyExport.py out of the XML file
// Every change you make here gets lost in the next full rebuild!
#ifndef PARTDESIGN_BODYPY_H
#define PARTDESIGN_BODYPY_H

#include <Mod/Part/App/BodyBasePy.h>
#include <Mod/PartDesign/App/Body.h>
#include <string>

namespace PartDesign
{

//===========================================================================
// BodyPy - Python wrapper
//===========================================================================

/** The python export class for Body
 */
class PartDesignExport BodyPy : public Part::BodyBasePy
{
protected:
    ~BodyPy();

public:
    static PyTypeObject   Type;
    static PyMethodDef    Methods[];
    static PyGetSetDef    GetterSetter[];
    virtual PyTypeObject *GetType(void) {return &Type;}

public:
    BodyPy(Body *pcObject, PyTypeObject *T = &Type);
    static PyObject *PyMake(struct _typeobject *, PyObject *, PyObject *);
    virtual int PyInit(PyObject* args, PyObject*k);


    typedef Body* PointerType ;

    virtual PyObject *_repr(void);        // the representation
    std::string representation(void) const;

    /** @name callbacks and implementers for the python object methods */
    //@{
    /// callback for the insertObject() method
    static PyObject * staticCallback_insertObject (PyObject *self, PyObject *args);
    /// implementer for the insertObject() method
    PyObject*  insertObject(PyObject *args);
    //@}


    /** @name callbacks and implementers for the python object attributes */
    //@{
    //@}

    /// getter method for special attributes (e.g. dynamic ones)
    PyObject *getCustomAttributes(const char* attr) const;
    /// setter for special attributes (e.g. dynamic ones)
    /// Output: Success=1, Failure=-1, Ignore=0
    int setCustomAttributes(const char* attr, PyObject *obj);
    PyObject *_getattr(const char *attr);              // __getattr__ function
    int _setattr(const char *attr, PyObject *value);        // __setattr__ function

    /// getter for the object handled by this class
    Body *getBodyPtr(void) const;

    /** @name additional declarations and methods for the wrapper class */
    //@{

    //@}
};

}  //namespace PartDesign

#endif  // PARTDESIGN_BODYPY_H


