
// This file is generated by src/Tools/generateTemaplates/templateClassPyExport.py out of the XML file
// Every change you make here gets lost in the next full rebuild!
#ifndef FEM_FEMPOSTPIPELINEPY_H
#define FEM_FEMPOSTPIPELINEPY_H

#include <App/GeoFeaturePy.h>
#include <Mod/Fem/App/FemPostPipeline.h>
#include <string>

namespace Fem
{

//===========================================================================
// FemPostPipelinePy - Python wrapper
//===========================================================================

/** The python export class for FemPostPipeline
 */
class FemExport FemPostPipelinePy : public App::GeoFeaturePy
{
protected:
    ~FemPostPipelinePy();

public:
    static PyTypeObject   Type;
    static PyMethodDef    Methods[];
    static PyGetSetDef    GetterSetter[];
    virtual PyTypeObject *GetType(void) {return &Type;}

public:
    FemPostPipelinePy(FemPostPipeline *pcObject, PyTypeObject *T = &Type);
    static PyObject *PyMake(struct _typeobject *, PyObject *, PyObject *);
    virtual int PyInit(PyObject* args, PyObject*k);


    typedef FemPostPipeline* PointerType ;

    virtual PyObject *_repr(void);        // the representation
    std::string representation(void) const;

    /** @name callbacks and implementers for the python object methods */
    //@{
    /// callback for the read() method
    static PyObject * staticCallback_read (PyObject *self, PyObject *args);
    /// implementer for the read() method
    PyObject*  read(PyObject *args);
    /// callback for the load() method
    static PyObject * staticCallback_load (PyObject *self, PyObject *args);
    /// implementer for the load() method
    PyObject*  load(PyObject *args);
    /// callback for the getLastPostObject() method
    static PyObject * staticCallback_getLastPostObject (PyObject *self, PyObject *args);
    /// implementer for the getLastPostObject() method
    PyObject*  getLastPostObject(PyObject *args);
    /// callback for the holdsPostObject() method
    static PyObject * staticCallback_holdsPostObject (PyObject *self, PyObject *args);
    /// implementer for the holdsPostObject() method
    PyObject*  holdsPostObject(PyObject *args);
    //@}


    /** @name callbacks and implementers for the python object attributes */
    //@{
    //@}

    /// getter method for special attributes (e.g. dynamic ones)
    PyObject *getCustomAttributes(const char* attr) const;
    /// setter for special attributes (e.g. dynamic ones)
    /// Output: Success=1, Failure=-1, Ignore=0
    int setCustomAttributes(const char* attr, PyObject *obj);
    PyObject *_getattr(const char *attr);              // __getattr__ function
    int _setattr(const char *attr, PyObject *value);        // __setattr__ function

    /// getter for the object handled by this class
    FemPostPipeline *getFemPostPipelinePtr(void) const;

    /** @name additional declarations and methods for the wrapper class */
    //@{

    //@}
};

}  //namespace Fem

#endif  // FEM_FEMPOSTPIPELINEPY_H


